version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: test123
            MYSQL_DATABASE: webzexperts
            MYSQL_USER: webzexperts
            MYSQL_PASSWORD: test123
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql_data:
